
#anchors = [float(x) for x in [10,14, 23,27, 37,58, 81,82, 135,169, 344,319]]
anchors = [10.0, 14.0, 23.0, 27.0, 37.0, 58.0, 81.0, 82.0, 135.0, 169.0, 344.0, 319.0]

classes = [
		  'person'
		, 'bicycle'
		, 'car'
		, 'motorbike'
		, 'aeroplane'
		, 'bus'
		, 'train'
		, 'truck'
		, 'boat'
		, 'traffic light'
		, 'fire hydrant'
		, 'stop sign'
		, 'parking meter'
		, 'bench'
		, 'bird'
		, 'cat'
		, 'dog'
		, 'horse'
		, 'sheep'
		, 'cow'
		, 'elephant'
		, 'bear'
		, 'zebra'
		, 'giraffe'
		, 'backpack'
		, 'umbrella'
		, 'handbag'
		, 'tie'
		, 'suitcase'
		, 'frisbee'
		, 'skis'
		, 'snowboard'
		, 'sports ball'
		, 'kite'
		, 'baseball bat'
		, 'baseball glove'
		, 'skateboard'
		, 'surfboard'
		, 'tennis racket'
		, 'bottle'
		, 'wine glass'
		, 'cup'
		, 'fork'
		, 'knife'
		, 'spoon'
		, 'bowl'
		, 'banana'
		, 'apple'
		, 'sandwich'
		, 'orange'
		, 'broccoli'
		, 'carrot'
		, 'hot dog'
		, 'pizza'
		, 'donut'
		, 'cake'
		, 'chair'
		, 'sofa'
		, 'pottedplant'
		, 'bed'
		, 'diningtable'
		, 'toilet'
		, 'tvmonitor'
		, 'laptop'
		, 'mouse'
		, 'remote'
		, 'keyboard'
		, 'cell phone'
		, 'microwave'
		, 'oven'
		, 'toaster'
		, 'sink'
		, 'refrigerator'
		, 'book'
		, 'clock'
		, 'vase'
		, 'scissors'
		, 'teddy bear'
		, 'hair drier'
		, 'toothbrush'
    ]